POST http://192.168.3.106:11434/v1/chat/completions
Authorization: Bearer OLLAMA
Content-Type: application/json

{
  "model": "gemma4:26b",
  "messages": [
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "temperature": 0.7,
  "stream": false
}

###

POST http://192.168.3.106:11434/v1/chat/completions
Authorization: Bearer OLLAMA
Content-Type: application/json

{
  "model": "gemma4:26b",
  "messages": [
    {
      "role": "user",
      "content": [
        { "type": "text", "text": "Опиши изображение" },
        { "type": "image_url", "image_url": { "url": "data:image/jpeg;base64,миллион байт" }}
      ]
    }
  ],
  "stream": false
}

###
